
```{r include = FALSE}
library(reticulate)

if(!knitr:::is_html_output())
{
  options("width"=56)
  knitr::opts_chunk$set(tidy.opts=list(width.cutoff=56, indent = 2), tidy = TRUE)
  knitr::opts_chunk$set(fig.pos = 'H')
}
```


# Introduction {#intro}

**Jupyter Lab**

to install on mac: `pip3 install jupyterlab` on terminal

to upgrade pip: `pip3 install --upgrade pip` on terminal

**check python version**
```{python, eval=F}
!python -V
```

**Python**

`Python` is what is called an interpreted language. Compiled languages examine your entire program at compile time, and are able to warn you about a whole class of errors prior to execution. In contrast, Python interprets your script line by line as it executes it. Python will stop executing the entire program when it encounters an error (unless the error is expected and handled by the programmer, a more advanced subject that we'll cover later on in this course).


```{python}
# Check the Python Version

import sys
print(sys.version)
```

[Tip:] `sys` is a built-in module that contains many system-specific parameters and functions, including the Python version in use. Before using it, we must explicitly import it.


## Types of objects in Python

Python is an object-oriented language. There are many different types of objects in Python. Let's start with the most common object types: strings, integers and floats. Anytime you write words (text) in Python, you're using character strings (strings for short). The most common numbers, on the other hand, are integers (e.g. -1, 0, 100) and floats, which represent real numbers (e.g. 3.14, -42.0).

**Object Types**

- integer = 10
- float = 10.1
- string = "Hello"
- boolean = True

**float to integer**

```{python}
a = 10.123
type(a)
```

```{python}
b = int(a)
b
```
```{python}
type(b)
```

**numeric to string**

```{python numst}
a_string = str(a)
a_string
```

**string to numeric**

```{python stnum}
float("1.1")
```

it does not transform directly to integer here

```{python, eval=F}
int("1.123")
```

but it works when transforming to float then integer.

```{python, eval=F}
int(float("10.123"))
```

**boolean**

```{python}
bl = True
bl
```

```{python}
type(bl)
```

**boolean to numeric**

`True` becomes 1
```{python bool1}
int(bl)
```

**numeric to boolean**

0 becomes `False`
all other numbers are `True`

```{python bool2}
bool(-100)
bool(0)
```

## Expressions: Mathematical Operations

```{python arith}
5 + 5 * 10  - 2 / 5
```

**integer division**
```{python div}
11 // 2   
```

**modulo: remainder**

```{python modulo}
10 % 3   
```

## String Operations

-string object are in single quote or double quote

### Indices

**Positive Index**
In python **indices** start with 0
In R **indices** start with 1

**Negative Index**
`-1` corresponds to the last element


```{python}
myname = "Davut Emrah Ayan"

print("Object myname:", myname)
# examples
print(myname[0], 'is the first element of myname object')
print(myname[6], 'is the 6th element of myname object')
print(myname[-1], 'is the last element of myname object')
```

### Slicing

**Full version**

object[from : to : increment]

```{python}
print("Object:", myname)

print("From 0 index to 5th index, by 1, is", myname[0:5:1])
```

**Short version**

```{python}
print("Object myname:", myname)
print(myname[0:5], "is the first 5 element of the object")
```

**Shorter version**

Numeric string is easier to see.
```{python}
num = "0123456789"
print(num[::2], "every 2 other element")
print(num[::3], "every 3 other element")
print(num[::4], "every 4 other element")
print(num[::5], "every 5 other element")
```

**Length** of an object : `len()`

it is character length or element length
```{python}
len(myname)
```


### Concatenate

```{python}
statement = "KU" + " is the best!"  
statement
```

```{python}
myname[0:5] + " is the best!"
```

**Multiplication with strings**

```{python}
myname[0:6] * 3
```

**Strings are Immutable**








